# Example: <Enter> still opens; <Ctrl-e> opens the file in $EDITOR in a split tmux pane (if tmux)
[[mgr.prepend_keymap]]
on = ["<C-e>"]
run = '''
sh -c '
if [ -n "$TMUX" ]; then
  tmux split-window -v -c "#{pane_current_path}" "${EDITOR:-nvim} \"$@\""
else
  ${EDITOR:-nvim} "$@"
fi
' -- $yx
'''
desc = "Open in $EDITOR (tmux split when available)"
