schema_version = 1

[domains]
primary = "suhail.ink"
additional = ["suhail.photos", "suhail.art", "suhail.life"]

[hosts.nexus]
kind = "physical"
roles = ["infrastructure", "dns", "proxy", "docker", "tailscale"]
runtime_root = "/var/lib/suhail/services/nexus"
ssh_user = "suhail"
enabled = true


[hosts.zion]
kind = "physical"
roles = ["proxmox"]
ssh_user = "root"
enabled = true

[hosts.zion.network]
provider = "proxmox-ifupdown2"
management_interface = "lan"
preserve_includes = true

[[hosts.zion.network.links]]
name = "enp3s0f0np0"
kind = "ethernet"

[[hosts.zion.network.links]]
name = "enp3s0f1np1"
kind = "ethernet"

[[hosts.zion.network.links]]
name = "enp88s0"
kind = "ethernet"

[[hosts.zion.network.links]]
name = "enp91s0"
kind = "ethernet"

[[hosts.zion.network.links]]
name = "wlp92s0"
kind = "wifi"

[[hosts.zion.network.bridges]]
name = "vmbr0"
ports = ["enp3s0f1np1"]
location_interface = "lan"
vlan_aware = true
allowed_vlans = "2-4094"
stp = false
forward_delay = 2
comment = "Primary"

[[hosts.zion.network.bridges]]
name = "vmbr1"
ports = []
vlan_aware = true
allowed_vlans = "2-4094"
stp = false
forward_delay = 2
comment = "VM & CT Network"

[hosts.atlas]
kind = "physical"
roles = ["proxmox"]
ssh_user = "root"
enabled = true

[hosts.atlas.network]
provider = "proxmox-ifupdown2"
management_interface = "lan"
preserve_includes = true

[[hosts.atlas.network.links]]
name = "enp2s0f0np0"
kind = "ethernet"

[[hosts.atlas.network.links]]
name = "enp2s0f1np1"
kind = "ethernet"

[[hosts.atlas.network.links]]
name = "enp87s0"
kind = "ethernet"

[[hosts.atlas.network.links]]
name = "enp88s0"
kind = "ethernet"

[[hosts.atlas.network.links]]
name = "wlp89s0"
kind = "wifi"

[[hosts.atlas.network.bridges]]
name = "vmbr0"
ports = ["enp2s0f0np0"]
location_interface = "lan"
vlan_aware = true
allowed_vlans = "2-4094"
stp = false
forward_delay = 2
comment = "Primary"

[[hosts.atlas.network.bridges]]
name = "vmbr1"
ports = []
vlan_aware = true
allowed_vlans = "2-4094"
stp = false
forward_delay = 2
comment = "VM & CT Network"

[hosts.summit]
kind = "physical"
roles = ["proxmox"]
ssh_user = "suhail"
enabled = false

[hosts.vortex]
kind = "vm"
parent = "zion"
roles = ["docker", "gpu", "development"]
runtime_root = "/var/lib/suhail/services/vortex"
ssh_user = "suhail"
enabled = true

[hosts.vortex.os_network]
provider = "netplan"
renderer = "networkd"
interface = "enp6s18"
ipv4_mode = "dhcp"
ipv6_mode = "router-advertised"


[hosts.eclipse]
kind = "laptop"
roles = ["client", "development"]
enabled = true


[hosts.quasar]
kind = "workstation"
roles = ["client", "development"]
ssh_user = "suhail"
enabled = true

[hosts.ds1621plus]
kind = "nas"
roles = ["storage"]
enabled = true
