# ~/.config/home/.pixi/manifests/pixi-global.toml

[global]
channels = ["conda-forge"]

# Always-on, cross-platform
[feature.base.dependencies]
ffmpeg = "*"
imagemagick = "*"
poppler = "*"
openexr = "*"
openimageio = "*"
libvips = "*"
opencv = "*"

# Optional buckets you can add to later
[feature.mac.dependencies]
# e.g., mac-only tools here

[feature.linux.dependencies]
# e.g., linux-only tools here
