# ~/.pixi/manifests/pixi-global.toml  (tracked in Bindu via stow)
# This file is YOUR schema (not Pixi’s). The helper script below reads it
# and calls `pixi global install` for the union of sets.

[channels]
# Optional extra channels to add to installs (pixi defaults to conda-forge already)
# channels = ["conda-forge"]

[sets.common]
packages = [
  "ffmpeg",
  "imagemagick",
  "poppler",         # macOS formula name; on Linux this is poppler-utils — pixi handles both via conda-forge
  "7zip",
  "openimageio",
  "libvips",
]

[sets.macos]
packages = [
  "pngpaste",
]

[sets.linux]
packages = [
  "xclip",
  "wl-clipboard",
]

# Host-specific adds (hostnames are short like your ORBIT_HOST)
[hosts.nimbus]
packages = [
  "cuda-toolkit",    # example
  # "cudnn",
]
