[channels]
# explicit is fine (pixi defaults to conda-forge anyway)
channels = ["conda-forge"]

[sets.common]
packages = [
  "ffmpeg",
  "imagemagick",
  "poppler",
  "p7zip",
  "openimageio",
  "libvips",
]

[sets.macos]
packages = [
  # "pngpaste",     # leave to Homebrew on macOS; comment out here
]

[sets.linux]
packages = [
  "xclip",
  "wl-clipboard",
]

[hosts.nimbus]
packages = [
  "cuda-toolkit",
]
